language: python
dist: trusty
sudo: required

python:
  - 2.7
  - 3.3
  - 3.4
env:
  - VIM_VERSION="74"
  - VIM_VERSION="git"

install:
   - ./travis_install.sh

script:
   - ./travis_test.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/558acac434012ba838cd
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
